version: '3.8'

services:
  db:
    image: mysql:8.0.20
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: profiles
      MYSQL_USER: empuser
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  profiles-app:
    image: shirenkov/m2k8s:latest
    volumes:
      - app-data:/data
    ports:
      - 8080:8080
    entrypoint: ["./wait-for-it.sh","db:3306", "--", "java", "-jar","app.jar" ]
    depends_on:
      - db

volumes:
  app-data:
  db-data: